export const SUBJECTS = [
  "Matrices and Calculus",
  "Advanced Engineering Physics / Applied Physics",
  "Programming for Problem Solving",
  "Basic Electrical Engineering",
  "Engineering Drawing / Computer Aided Engineering Graphics / Computer Aided Drafting",
  "Elements of Computer Science & Engineering",
  "Engineering Chemistry",
  "Ordinary Differential Equations and Vector Calculus",
  "Data Structures",
  "Electronic Devices and Circuits",
  "English for Skill Enhancement",
  "Python Programming Laboratory",
  "Applied Physics / Engineering Physics Laboratory",
  "English Language and Communication Skills Laboratory",
  "IT Workshop",
  "Engineering Workshop / Engineering Chemistry Lab",
  "Programming for Problem Solving Laboratory",
  "Basic Electrical Engineering Laboratory",
  "Digital Electronics",
  "Computer Oriented Statistical Methods / Mathematical and Statistical Foundations / Computational Mathematics",
  "Computer Organization and Architecture",
  "Object Oriented Programming through Java",
  "Data Structures Lab",
  "Object Oriented Programming through Java Lab",
  "Data Visualization (R Programming / Power BI) - Skill Development Course",
  "Discrete Mathematics",
  "Business Economics & Financial Analysis",
  "Operating Systems",
  "Database Management Systems",
  "Software Engineering",
  "Operating Systems Lab",
  "Database Management Systems Lab",
  "Design and Analysis of Algorithms / Algorithm Design and Analysis",
  "Computer Networks",
  "DevOps",
  "Computer Networks Lab",
  "DevOps Lab",
  "Advanced English Communication Skills Lab / English for Employability Skills Lab",
  "Formal Languages and Automata Theory / Automata Theory and Compiler Design",
  "Machine Learning / Artificial Intelligence",
  "Machine Learning Lab / AI Lab",
  "Compiler Design",
  "Cryptography and Network Security",
  "Project Stage - I",
  "Project Stage - II / Project Work (Major Project + Seminar)",
  "Industrial Oriented Mini Project / Internship / Field Based Research Project",
  "Reinforcement Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Generative AI",
  "Data Analytics and Visualization",
  "Prompt Engineering",
  "Chatbots Lab",
  "UI Design (Flutter / Android Studio)",
  "Innovation and Entrepreneurship",
  "Fundamentals of Management for Engineers",
  "Indian Knowledge System",
  "Environmental Science",
  "Constitution of India",
  "Intellectual Property Rights",
  "Gender Sensitization / Human Values and Professional Ethics",
  
  // Professional Electives
  "Cloud Computing",
  "Blockchain Technology",
  "Full Stack Development",
  "Data Analytics / Data Mining",
  "Deep Learning",
  "Internet of Things",
  "Software Testing Methodologies",
  "Computer Graphics",
  "Ad hoc & Sensor Networks",
  "Advanced Algorithms",
  "Graph Theory",
  "Cyber Security / Cryptography",
  "Natural Language Processing",
  "Distributed Systems",
  "Mobile Application Development",
  "Big Data Technologies",
  "Quantum Computing",
  "Robotic Process Automation",
  "Nature Inspired Computing",
  "Image Processing",
  "Web Programming / Technologies",
  "Augmented Reality & Virtual Reality",
  "Agile Methodology",
  "Software Project Management",
  "Human Computer Interaction",
  "Computational Complexity",
  "Information Retrieval Systems",
  "Game Theory",
  "Edge Computing",
  "Computer Vision",
  "Penetration Testing and Incident Response",
  "Data Stream Mining",
  "Social Media Mining",
  "Cyber Forensics",
  "High Performance Computing",
  "Distributed Databases",
  "Sustainable Engineering",

  // Open Electives
  "Fundamentals of AI",
  "Introduction to Data Science",
  "Data Structures (for non-CSE)",
  "DBMS",
  "Operating Systems",
  "Software Engineering",
  "Computer Networks",
  "Introduction to Natural Language Processing",
  "AI Applications",
  "Chatbots",
  "Computer Vision with OpenCV"
];
